services:
  - type: web
    name: app
    env: node
    buildCommand: npm install
    startCommand: npm run start
    plan: free
    branches: ["main"]
    rootDirectory: "/app"  # Make sure this points to your frontend directory

  - type: web
    name: backend
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: python backend/api.py
    plan: free
    branches: ["main"]
    rootDirectory: "/backend"  # Make sure this points to your backend directory
